version: "3.7"

services:
  emulator:
    image: badrap/emulator:v0.6.0
    environment:
      APP_URL: http://app:4005/app
    ports:
      - "4004:4004"

  app:
    image: node:13.10.1-alpine
    command: /bin/sh -c 'yarn --frozen-lockfile && yarn dev'
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      SERVER_URL: http://emulator:4004
      APP_TOKEN: "111111111-2222-3333-44444-555555555555"
    ports:
      - "4005:4005"
